name: keiretsuforum
favicon: null
layout_spectrum: 0
typography_spectrum: 0.35019
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f1e1d'
    - '#fc0a16'
    - '#ffffff'
    - '#737271'
    - '#d5d4d4'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
