name: keiretsuforum
favicon: null
layout_spectrum: 0.9799215940292925
typography_spectrum: 0.12067749304696918
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.21225851774215698
  lightness: 0.4734451174736023
  saturation: 0.12685763370245695
  rhythmicContrast: 0.9946905833203346
purpose: []
